export interface SubLetterItem {
    letter: string;
    page: number;
    targetPage?: number;
}

export interface IndexItem {
    id: number;
    title: string;
    letterKey: string;
    page: number;
    targetPage?: number;
    subLetters?: SubLetterItem[];
}

export const PDF_INDEX: IndexItem[] = [
    {
        id: 1,
        title: "اٰ",
        letterKey: "اٰ",
        page: 3,
        targetPage: 4,
        subLetters: [
            { letter: "ب", page: 3, targetPage: 4 },
            { letter: "ت", page: 3, targetPage: 4 },
            { letter: "ث", page: 3, targetPage: 4 },
            { letter: "خ", page: 4, targetPage: 5 },
            { letter: "د", page: 4, targetPage: 5 },
            { letter: "ذ", page: 4, targetPage: 5 },
            { letter: "ز", page: 4, targetPage: 5 },
            { letter: "س", page: 4, targetPage: 5 },
            { letter: "ص", page: 4, targetPage: 5 },
            { letter: "ف", page: 4, targetPage: 5 },
            { letter: "ک", page: 5, targetPage: 6 },
            { letter: "ل", page: 5, targetPage: 6 },
            { letter: "م", page: 5, targetPage: 6 },
            { letter: "ن", page: 5, targetPage: 6 },
            { letter: "و", page: 5, targetPage: 6 },
            { letter: "ی", page: 6, targetPage: 7 },
        ]
    },
    {
        id: 2,
        title: "ا (الف)",
        letterKey: "ا",
        page: 6,
        targetPage: 7,
        subLetters: [
            { letter: "ء", page: 6, targetPage: 7 },
            { letter: "ب", page: 6, targetPage: 7 },
            { letter: "ت", page: 8, targetPage: 9 },
            { letter: "ث", page: 10, targetPage: 11 },
            { letter: "ج", page: 11, targetPage: 12 },
            { letter: "ح", page: 12, targetPage: 13 },
            { letter: "خ", page: 15, targetPage: 16 },
            { letter: "د", page: 17, targetPage: 18 },
            { letter: "ذ", page: 18, targetPage: 19 },
            { letter: "ر", page: 19, targetPage: 20 },
            { letter: "ز", page: 22, targetPage: 23 },
            { letter: "س", page: 23, targetPage: 24 },
            { letter: "ش", page: 29, targetPage: 30 },
            { letter: "ص", page: 31, targetPage: 32 },
            { letter: "ض", page: 34, targetPage: 35 },
            { letter: "ط", page: 34, targetPage: 35 },
            { letter: "ظ", page: 35, targetPage: 36 },
            { letter: "ع", page: 36, targetPage: 37 },
            { letter: "غ", page: 39, targetPage: 40 },
            { letter: "ف", page: 39, targetPage: 40 },
            { letter: "ق", page: 41, targetPage: 42 },
            { letter: "ک", page: 43, targetPage: 44 },
            { letter: "ل", page: 45, targetPage: 46 },
            { letter: "م", page: 48, targetPage: 49 },
            { letter: "ن", page: 51, targetPage: 52 },
            { letter: "و", page: 56, targetPage: 57 },
            { letter: "ھ", page: 58, targetPage: 59 },
            { letter: "ی", page: 60, targetPage: 61 },
        ]
    },
    {
        id: 3,
        title: "ب",
        letterKey: "ب",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ء", page: 61, targetPage: 62 },
            { letter: "ا", page: 61, targetPage: 62 },
            { letter: "ث", page: 63, targetPage: 64 },
            { letter: "ح", page: 63, targetPage: 64 },
            { letter: "خ", page: 63, targetPage: 64 },
            { letter: "د", page: 63, targetPage: 64 },
            { letter: "ر", page: 64, targetPage: 65 },
            { letter: "س", page: 65, targetPage: 66 },
            { letter: "ش", page: 65, targetPage: 66 },
            { letter: "ص", page: 66, targetPage: 67 },
            { letter: "ض", page: 66, targetPage: 67 },
            { letter: "ط", page: 66, targetPage: 67 },
            { letter: "ع", page: 66, targetPage: 67 },
            { letter: "غ", page: 67, targetPage: 68 },
            { letter: "ق", page: 67, targetPage: 68 },
            { letter: "ک", page: 68, targetPage: 69 },
            { letter: "ل", page: 68, targetPage: 69 },
            { letter: "م", page: 69, targetPage: 70 },
            { letter: "ن", page: 69, targetPage: 70 },
            { letter: "و", page: 69, targetPage: 70 },
            { letter: "ھ", page: 70, targetPage: 71 },
            { letter: "ی", page: 70, targetPage: 71 },
        ]
    },
    {
        id: 4,
        title: "ت",
        letterKey: "ت",
        page: 71,
        targetPage: 72,
        subLetters: [
            { letter: "ا", page: 71, targetPage: 72 },
            { letter: "ب", page: 73, targetPage: 74 },
            { letter: "ت", page: 75, targetPage: 76 },
            { letter: "ث", page: 77, targetPage: 78 },
            { letter: "ج", page: 77, targetPage: 78 },
            { letter: "ح", page: 78, targetPage: 79 },
            { letter: "خ", page: 81, targetPage: 82 },
            { letter: "د", page: 83, targetPage: 84 },
            { letter: "ذ", page: 84, targetPage: 85 },
            { letter: "ر", page: 85, targetPage: 86 },
            { letter: "ز", page: 87, targetPage: 88 },
            { letter: "س", page: 88, targetPage: 89 },
            { letter: "ش", page: 92, targetPage: 93 },
            { letter: "ص", page: 93, targetPage: 94 },
            { letter: "ض", page: 95, targetPage: 96 },
            { letter: "ط", page: 96, targetPage: 97 },
            { letter: "ظ", page: 97, targetPage: 98 },
            { letter: "ع", page: 98, targetPage: 99 },
            { letter: "غ", page: 101, targetPage: 102 },
            { letter: "ف", page: 101, targetPage: 102 },
            { letter: "ق", page: 103, targetPage: 104 },
            { letter: "ک", page: 106, targetPage: 107 },
            { letter: "ل", page: 108, targetPage: 109 },
            { letter: "م", page: 109, targetPage: 110 },
            { letter: "ن", page: 111, targetPage: 112 },
            { letter: "و", page: 115, targetPage: 116 },
            { letter: "ھ", page: 118, targetPage: 119 },
            { letter: "ی", page: 118, targetPage: 119 },
        ]
    },
    {
        id: 5,
        title: "ث",
        letterKey: "ث",
        page: 119,
        targetPage: 120,
        subLetters: [
            { letter: "ا", page: 119, targetPage: 120 },
            { letter: "ب", page: 119, targetPage: 120 },
            { letter: "ج", page: 119, targetPage: 120 },
            { letter: "ر", page: 119, targetPage: 120 },
            { letter: "ع", page: 119, targetPage: 120 },
            { letter: "ق", page: 119, targetPage: 120 },
            { letter: "ل", page: 119, targetPage: 120 },
            { letter: "م", page: 120, targetPage: 121 },
            { letter: "و", page: 120, targetPage: 121 },
            { letter: "ی", page: 120, targetPage: 121 },
        ]
    },
    {
        id: 6,
        title: "ج",
        letterKey: "ج",
        page: 120,
        targetPage: 121,
        subLetters: [
            { letter: "آ", page: 120, targetPage: 121 },
            { letter: "ء", page: 120, targetPage: 121 },
            { letter: "ا", page: 121, targetPage: 122 },
            { letter: "ب", page: 122, targetPage: 123 },
            { letter: "ث", page: 122, targetPage: 123 },
            { letter: "ح", page: 122, targetPage: 123 },
            { letter: "د", page: 122, targetPage: 123 },
            { letter: "ذ", page: 123, targetPage: 124 },
            { letter: "ر", page: 123, targetPage: 124 },
            { letter: "ز", page: 123, targetPage: 124 },
            { letter: "س", page: 124, targetPage: 125 },
            { letter: "ع", page: 124, targetPage: 125 },
            { letter: "ف", page: 124, targetPage: 125 },
            { letter: "ل", page: 124, targetPage: 125 },
            { letter: "م", page: 124, targetPage: 125 },
            { letter: "ن", page: 125, targetPage: 126 },
            { letter: "و", page: 126, targetPage: 127 },
            { letter: "ھ", page: 126, targetPage: 127 },
            { letter: "ی", page: 126, targetPage: 127 },
        ]
    },
    {
        id: 7,
        title: "ح",
        letterKey: "ح",
        page: 127,
        targetPage: 128,
        subLetters: [
            { letter: "آ", page: 127, targetPage: 128 },
            { letter: "ا", page: 127, targetPage: 128 },
            { letter: "ب", page: 129, targetPage: 130 },
            { letter: "ت", page: 129, targetPage: 130 },
            { letter: "ث", page: 129, targetPage: 130 },
            { letter: "ج", page: 129, targetPage: 130 },
            { letter: "د", page: 130, targetPage: 131 },
            { letter: "ذ", page: 130, targetPage: 131 },
            { letter: "ر", page: 130, targetPage: 131 },
            { letter: "ز", page: 131, targetPage: 132 },
            { letter: "س", page: 131, targetPage: 132 },
            { letter: "ش", page: 132, targetPage: 133 },
            { letter: "ص", page: 132, targetPage: 133 },
            { letter: "ض", page: 133, targetPage: 134 },
            { letter: "ط", page: 133, targetPage: 134 },
            { letter: "ظ", page: 133, targetPage: 134 },
            { letter: "ف", page: 133, targetPage: 134 },
            { letter: "ق", page: 133, targetPage: 134 },
            { letter: "ک", page: 134, targetPage: 135 },
            { letter: "ل", page: 134, targetPage: 135 },
            { letter: "م", page: 135, targetPage: 136 },
            { letter: "ن", page: 135, targetPage: 136 },
            { letter: "و", page: 136, targetPage: 137 },
            { letter: "ی", page: 136, targetPage: 137 },
        ]
    },
    {
        id: 8,
        title: "خ",
        letterKey: "خ",
        page: 137,
        targetPage: 138,
        subLetters: [
            { letter: "آ", page: 137, targetPage: 138 },
            { letter: "ا", page: 137, targetPage: 138 },
            { letter: "ب", page: 139, targetPage: 140 },
            { letter: "ت", page: 140, targetPage: 141 },
            { letter: "د", page: 140, targetPage: 141 },
            { letter: "ذ", page: 140, targetPage: 141 },
            { letter: "ر", page: 140, targetPage: 141 },
            { letter: "ز", page: 141, targetPage: 142 },
            { letter: "س", page: 141, targetPage: 142 },
            { letter: "ش", page: 141, targetPage: 142 },
            { letter: "ص", page: 141, targetPage: 142 },
            { letter: "ض", page: 141, targetPage: 142 },
            { letter: "ط", page: 142, targetPage: 143 },
            { letter: "ف", page: 142, targetPage: 143 },
            { letter: "ل", page: 142, targetPage: 143 },
            { letter: "م", page: 144, targetPage: 145 },
            { letter: "ن", page: 144, targetPage: 145 },
            { letter: "و", page: 144, targetPage: 145 },
            { letter: "ی", page: 144, targetPage: 145 },
        ]
    },
    {
        id: 9,
        title: "د",
        letterKey: "د",
        page: 145,
        targetPage: 146,
        subLetters: [
            { letter: "آ", page: 145, targetPage: 146 },
            { letter: "ا", page: 145, targetPage: 146 },
            { letter: "ب", page: 146, targetPage: 147 },
            { letter: "ح", page: 146, targetPage: 147 },
            { letter: "خ", page: 146, targetPage: 147 },
            { letter: "ر", page: 146, targetPage: 147 },
            { letter: "س", page: 147, targetPage: 148 },
            { letter: "ع", page: 147, targetPage: 148 },
            { letter: "ف", page: 147, targetPage: 148 },
            { letter: "ک", page: 147, targetPage: 148 },
            { letter: "ل", page: 148, targetPage: 149 },
            { letter: "م", page: 148, targetPage: 149 },
            { letter: "ن", page: 148, targetPage: 149 },
            { letter: "و", page: 148, targetPage: 149 },
            { letter: "ھ", page: 148, targetPage: 149 },
            { letter: "ی", page: 148, targetPage: 149 },
        ]
    },
    {
        id: 10,
        title: "ذ",
        letterKey: "ذ",
        page: 149,
        targetPage: 150,
        subLetters: [
            { letter: "آ", page: 149, targetPage: 150 },
            { letter: "ا", page: 149, targetPage: 150 },
            { letter: "ب", page: 150, targetPage: 149 },
            { letter: "ر", page: 150, targetPage: 151 },
            { letter: "ق", page: 150, targetPage: 151 },
            { letter: "ک", page: 150, targetPage: 151 },
            { letter: "ل", page: 151, targetPage: 152 },
            { letter: "م", page: 151, targetPage: 152 },
            { letter: "ن", page: 151, targetPage: 152 },
            { letter: "و", page: 151, targetPage: 152 },
            { letter: "ھ", page: 152, targetPage: 153 },
            { letter: "ی", page: 152, targetPage: 153 },
        ]
    },
    {
        id: 11,
        title: "ر",
        letterKey: "ر",
        page: 152,
        targetPage: 153,
        subLetters: [
            { letter: "ء", page: 152, targetPage: 153 },
            { letter: "ا", page: 152, targetPage: 153 },
            { letter: "ب", page: 154, targetPage: 155 },
            { letter: "ت", page: 155, targetPage: 156 },
            { letter: "ج", page: 155, targetPage: 156 },
            { letter: "ح", page: 156, targetPage: 157 },
            { letter: "خ", page: 157, targetPage: 158 },
            { letter: "د", page: 157, targetPage: 158 },
            { letter: "ز", page: 157, targetPage: 158 },
            { letter: "س", page: 157, targetPage: 158 },
            { letter: "ش", page: 157, targetPage: 158 },
            { letter: "ص", page: 158, targetPage: 159 },
            { letter: "ض", page: 158, targetPage: 159 },
            { letter: "ط", page: 158, targetPage: 159 },
            { letter: "ع", page: 158, targetPage: 159 },
            { letter: "غ", page: 158, targetPage: 159 },
            { letter: "ف", page: 158, targetPage: 159 },
            { letter: "ق", page: 159, targetPage: 160 },
            { letter: "ک", page: 159, targetPage: 160 },
            { letter: "م", page: 159, targetPage: 160 },
            { letter: "و", page: 160, targetPage: 161 },
            { letter: "ھ", page: 160, targetPage: 161 },
            { letter: "ی", page: 161, targetPage: 162 },
        ]
    },
    {
        id: 12,
        title: "ز",
        letterKey: "ز",
        page: 161,
        targetPage: 162,
        subLetters: [
            { letter: "ا", page: 161, targetPage: 162 },
            { letter: "ب", page: 162, targetPage: 163 },
            { letter: "ج", page: 162, targetPage: 163 },
            { letter: "ح", page: 163, targetPage: 164 },
            { letter: "خ", page: 163, targetPage: 164 },
            { letter: "د", page: 163, targetPage: 164 },
            { letter: "ر", page: 163, targetPage: 164 },
            { letter: "ع", page: 163, targetPage: 164 },
            { letter: "ف", page: 163, targetPage: 164 },
            { letter: "ق", page: 163, targetPage: 164 },
            { letter: "ک", page: 163, targetPage: 164 },
            { letter: "ل", page: 164, targetPage: 165 },
            { letter: "م", page: 164, targetPage: 165 },
            { letter: "ن", page: 164, targetPage: 165 },
            { letter: "و", page: 164, targetPage: 165 },
            { letter: "ھ", page: 165, targetPage: 166 },
            { letter: "ی", page: 165, targetPage: 166 },
        ]
    },
    {
        id: 13,
        title: "س",
        letterKey: "س",
        page: 166,
        targetPage: 167,
        subLetters: [
            { letter: "آ", page: 166, targetPage: 167 },
            { letter: "ا", page: 167, targetPage: 168 },
            { letter: "ب", page: 169, targetPage: 170 },
            { letter: "ت", page: 170, targetPage: 171 },
            { letter: "ج", page: 171, targetPage: 172 },
            { letter: "ح", page: 171, targetPage: 172 },
            { letter: "خ", page: 172, targetPage: 173 },
            { letter: "د", page: 172, targetPage: 173 },
            { letter: "ر", page: 172, targetPage: 173 },
            { letter: "ط", page: 173, targetPage: 174 },
            { letter: "ع", page: 173, targetPage: 174 },
            { letter: "ف", page: 174, targetPage: 175 },
            { letter: "ق", page: 174, targetPage: 175 },
            { letter: "ک", page: 175, targetPage: 176 },
            { letter: "ل", page: 175, targetPage: 176 },
            { letter: "م", page: 177, targetPage: 178 },
            { letter: "ن", page: 178, targetPage: 179 },
            { letter: "و", page: 178, targetPage: 179 },
            { letter: "ھ", page: 180, targetPage: 181 },
            { letter: "ی", page: 180, targetPage: 181 },
        ]
    },
    {
        id: 14,
        title: "ش",
        letterKey: "ش",
        page: 181,
        targetPage: 182,
        subLetters: [
            { letter: "آ", page: 181, targetPage: 182 },
            { letter: "ء", page: 181, targetPage: 182 },
            { letter: "ا", page: 181, targetPage: 182 },
            { letter: "ب", page: 182, targetPage: 183 },
            { letter: "ت", page: 182, targetPage: 183 },
            { letter: "ج", page: 183, targetPage: 184 },
            { letter: "ح", page: 183, targetPage: 184 },
            { letter: "د", page: 183, targetPage: 184 },
            { letter: "ر", page: 183, targetPage: 184 },
            { letter: "ط", page: 184, targetPage: 185 },
            { letter: "ع", page: 184, targetPage: 185 },
            { letter: "غ", page: 185, targetPage: 186 },
            { letter: "ف", page: 185, targetPage: 186 },
            { letter: "ق", page: 186, targetPage: 187 },
            { letter: "ک", page: 186, targetPage: 187 },
            { letter: "م", page: 186, targetPage: 187 },
            { letter: "ن", page: 187, targetPage: 188 },
            { letter: "و", page: 187, targetPage: 188 },
            { letter: "ھ", page: 187, targetPage: 188 },
            { letter: "ی", page: 188, targetPage: 189 },
        ]
    },
    {
        id: 15,
        title: "ص",
        letterKey: "ص",
        page: 189,
        targetPage: 192,
        subLetters: [
            { letter: "آ", page: 189, targetPage: 190 },
            { letter: "ا", page: 189, targetPage: 190 },
            { letter: "ب", page: 191, targetPage: 192 },
            { letter: "ح", page: 192, targetPage: 193 },
            { letter: "خ", page: 192, targetPage: 193 },
            { letter: "د", page: 192, targetPage: 193 },
            { letter: "ر", page: 194, targetPage: 195 },
            { letter: "ع", page: 195, targetPage: 196 },
            { letter: "غ", page: 195, targetPage: 196 },
            { letter: "ف", page: 195, targetPage: 196 },
            { letter: "ک", page: 195, targetPage: 196 },
            { letter: "ل", page: 196, targetPage: 197 },
            { letter: "م", page: 196, targetPage: 197 },
            { letter: "ن", page: 197, targetPage: 198 },
            { letter: "و", page: 197, targetPage: 198 },
            { letter: "ھ", page: 197, targetPage: 198 },
            { letter: "ی", page: 198, targetPage: 199 },
        ]
    },
    {
        id: 16,
        title: "ض",
        letterKey: "ض",
        page: 198,
        targetPage: 199,
        subLetters: [
            { letter: "آ", page: 198, targetPage: 199 },
            { letter: "ا", page: 198, targetPage: 199 },
            { letter: "ب", page: 199, targetPage: 200 },
            { letter: "ح", page: 199, targetPage: 200 },
            { letter: "د", page: 199, targetPage: 200 },
            { letter: "ر", page: 199, targetPage: 200 },
            { letter: "ع", page: 199, targetPage: 200 },
            { letter: "غ", page: 200, targetPage: 201 },
            { letter: "ف", page: 200, targetPage: 201 },
            { letter: "ل", page: 200, targetPage: 201 },
            { letter: "ن", page: 200, targetPage: 201 },
            { letter: "ی", page: 200, targetPage: 201 },
        ]
    },
    {
        id: 17,
        title: "ط",
        letterKey: "ط",
        page: 201,
        targetPage: 202,
        subLetters: [
            { letter: "آ", page: 201, targetPage: 202 },
            { letter: "ا", page: 201, targetPage: 202 },
            { letter: "ب", page: 202, targetPage: 203 },
            { letter: "ح", page: 203, targetPage: 204 },
            { letter: "ر", page: 203, targetPage: 204 },
            { letter: "س", page: 203, targetPage: 204 },
            { letter: "ع", page: 203, targetPage: 204 },
            { letter: "غ", page: 204, targetPage: 205 },
            { letter: "ف", page: 204, targetPage: 205 },
            { letter: "ل", page: 204, targetPage: 205 },
            { letter: "م", page: 205, targetPage: 206 },
            { letter: "و", page: 205, targetPage: 206 },
            { letter: "ھ", page: 206, targetPage: 207 },
            { letter: "ی", page: 206, targetPage: 207 },
        ]
    },
    {
        id: 18,
        title: "ظ",
        letterKey: "ظ",
        page: 207,
        targetPage: 208,
        subLetters: [
            { letter: "ا", page: 207, targetPage: 208 },
            { letter: "ع", page: 207, targetPage: 208 },
            { letter: "ف", page: 207, targetPage: 208 },
            { letter: "ل", page: 207, targetPage: 208 },
            { letter: "م", page: 209, targetPage: 210 },
            { letter: "ن", page: 209, targetPage: 210 },
            { letter: "ھ", page: 209, targetPage: 210 },
        ]
    },
    {
        id: 19,
        title: "ع",
        letterKey: "ع",
        page: 209,
        targetPage: 210,
        subLetters: [
            { letter: "آ", page: 210, targetPage: 211 },
            { letter: "ا", page: 210, targetPage: 211 },
            { letter: "ب", page: 213, targetPage: 214 },
            { letter: "ت", page: 214, targetPage: 215 },
            { letter: "ث", page: 215, targetPage: 216 },
            { letter: "ج", page: 215, targetPage: 216 },
            { letter: "د", page: 215, targetPage: 216 },
            { letter: "ذ", page: 217, targetPage: 218 },
            { letter: "ر", page: 217, targetPage: 218 },
            { letter: "ز", page: 219, targetPage: 220 },
            { letter: "س", page: 220, targetPage: 221 },
            { letter: "ش", page: 220, targetPage: 221 },
            { letter: "ص", page: 221, targetPage: 222 },
            { letter: "ض", page: 221, targetPage: 222 },
            { letter: "ط", page: 221, targetPage: 222 },
            { letter: "ظ", page: 222, targetPage: 223 },
            { letter: "ف", page: 222, targetPage: 223 },
            { letter: "ق", page: 222, targetPage: 223 },
            { letter: "ل", page: 223, targetPage: 224 },
            { letter: "م", page: 224, targetPage: 225 },
            { letter: "ن", page: 226, targetPage: 227 },
            { letter: "و", page: 226, targetPage: 227 },
            { letter: "ھ", page: 226, targetPage: 227 },
            { letter: "ی", page: 226, targetPage: 227 },
        ]
    },
    {
        id: 20,
        title: "غ",
        letterKey: "غ",
        page: 227,
        targetPage: 228,
        subLetters: [
            { letter: "آ", page: 227, targetPage: 228 },
            { letter: "ا", page: 227, targetPage: 228 },
            { letter: "ب", page: 228, targetPage: 229 },
            { letter: "ث", page: 228, targetPage: 229 },
            { letter: "د", page: 228, targetPage: 229 },
            { letter: "ر", page: 228, targetPage: 229 },
            { letter: "ز", page: 229, targetPage: 230 },
            { letter: "س", page: 229, targetPage: 230 },
            { letter: "ش", page: 229, targetPage: 230 },
            { letter: "ص", page: 229, targetPage: 230 },
            { letter: "ض", page: 229, targetPage: 230 },
            { letter: "ط", page: 229, targetPage: 230 },
            { letter: "ف", page: 229, targetPage: 230 },
            { letter: "ل", page: 230, targetPage: 231 },
            { letter: "م", page: 230, targetPage: 231 },
            { letter: "ن", page: 230, targetPage: 231 },
            { letter: "و", page: 231, targetPage: 232 },
            { letter: "ی", page: 231, targetPage: 232 },
        ]
    },
    {
        id: 21,
        title: "ف",
        letterKey: "ف",
        page: 231,
        targetPage: 223,
        subLetters: [
            { letter: "آ", page: 231, targetPage: 232 },
            { letter: "ء", page: 232, targetPage: 233 },
            { letter: "ا", page: 232, targetPage: 233 },
            { letter: "ت", page: 233, targetPage: 234 },
            { letter: "ج", page: 234, targetPage: 235 },
            { letter: "ح", page: 234, targetPage: 235 },
            { letter: "خ", page: 234, targetPage: 235 },
            { letter: "د", page: 234, targetPage: 235 },
            { letter: "ر", page: 234, targetPage: 235 },
            { letter: "ز", page: 237, targetPage: 238 },
            { letter: "س", page: 237, targetPage: 238 },
            { letter: "ش", page: 237, targetPage: 238 },
            { letter: "ص", page: 237, targetPage: 238 },
            { letter: "ض", page: 238, targetPage: 239 },
            { letter: "ط", page: 238, targetPage: 239 },
            { letter: "ظ", page: 238, targetPage: 239 },
            { letter: "ع", page: 238, targetPage: 239 },
            { letter: "ق", page: 239, targetPage: 240 },
            { letter: "ک", page: 239, targetPage: 240 },
            { letter: "ل", page: 239, targetPage: 240 },
            { letter: "و", page: 239, targetPage: 240 },
            { letter: "ھ", page: 239, targetPage: 240 },
            { letter: "ی", page: 239, targetPage: 240 },
        ]
    },
    {
        id: 22,
        title: "ق",
        letterKey: "ق",
        page: 239,
        targetPage: 240,
        subLetters: [
            { letter: "آ", page: 239, targetPage: 240 },
            { letter: "ا", page: 240, targetPage: 241 },
            { letter: "ب", page: 242, targetPage: 243 },
            { letter: "ت", page: 242, targetPage: 243 },
            { letter: "ث", page: 243, targetPage: 244 },
            { letter: "د", page: 243, targetPage: 244 },
            { letter: "ذ", page: 244, targetPage: 245 },
            { letter: "ر", page: 245, targetPage: 246 },
            { letter: "س", page: 246, targetPage: 247 },
            { letter: "ص", page: 246, targetPage: 247 },
            { letter: "ض", page: 247, targetPage: 248 },
            { letter: "ط", page: 247, targetPage: 248 },
            { letter: "ع", page: 248, targetPage: 249 },
            { letter: "ف", page: 248, targetPage: 249 },
            { letter: "ل", page: 248, targetPage: 249 },
            { letter: "م", page: 249, targetPage: 250 },
            { letter: "ن", page: 249, targetPage: 250 },
            { letter: "و", page: 249, targetPage: 250 },
            { letter: "ھ", page: 250, targetPage: 251 },
            { letter: "ی", page: 250, targetPage: 251 },
        ]
    },
    {
        id: 23,
        title: " ک",
        letterKey: " ک",
        page: 251,
        targetPage: 252,
        subLetters: [
            { letter: "ا", page: 251, targetPage: 252 },
            { letter: "ب", page: 252, targetPage: 253 },
            { letter: "ت", page: 253, targetPage: 254 },
            { letter: "ث", page: 254, targetPage: 255 },
            { letter: "د", page: 254, targetPage: 255 },
            { letter: "ذ", page: 254, targetPage: 255 },
            { letter: "ر", page: 255, targetPage: 256 },
            { letter: "س", page: 255, targetPage: 256 },
            { letter: "ش", page: 256, targetPage: 257 },
            { letter: "ظ", page: 256, targetPage: 257 },
            { letter: "ع", page: 256, targetPage: 257 },
            { letter: "ف", page: 256, targetPage: 257 },
            { letter: "ل", page: 257, targetPage: 258 },
            { letter: "م", page: 258, targetPage: 259 },
            { letter: "ن", page: 258, targetPage: 259 },
            { letter: "و", page: 259, targetPage: 260 },
            { letter: "ھ", page: 259, targetPage: 260 },
            { letter: "ی", page: 259, targetPage: 260 },
        ]
    },
    {
        id: 24,
        title: "ل",
        letterKey: "ل",
        page: 259,
        targetPage: 260,
        subLetters: [
            { letter: "ا", page: 259, targetPage: 260 },
            { letter: "ب", page: 261, targetPage: 262 },
            { letter: "ج", page: 262, targetPage: 263 },
            { letter: "ح", page: 262, targetPage: 263 },
            { letter: "د", page: 262, targetPage: 263 },
            { letter: "ذ", page: 262, targetPage: 263 },
            { letter: "ز", page: 262, targetPage: 263 },
            { letter: "س", page: 262, targetPage: 263 },
            { letter: "ط", page: 262, targetPage: 263 },
            { letter: "ظ", page: 262, targetPage: 263 },
            { letter: "ع", page: 262, targetPage: 263 },
            { letter: "غ", page: 263, targetPage: 264 },
            { letter: "ف", page: 263, targetPage: 264 },
            { letter: "ق", page: 263, targetPage: 264 },
            { letter: "ک", page: 263, targetPage: 264 },
            { letter: "م", page: 263, targetPage: 264 },
            { letter: "ن", page: 264, targetPage: 265 },
            { letter: "و", page: 264, targetPage: 265 },
            { letter: "ھ", page: 264, targetPage: 265 },
            { letter: "ی", page: 265, targetPage: 266 },
        ]
    },
    {
        id: 25,
        title: "م",
        letterKey: "م",
        page: 266,
        targetPage: 267,
        subLetters: [
            { letter: "آ", page: 266, targetPage: 267 },
            { letter: "ا", page: 266, targetPage: 267 },
            { letter: "ب", page: 268, targetPage: 269 },
            { letter: "ت", page: 269, targetPage: 270 },
            { letter: "ث", page: 272, targetPage: 273 },
            { letter: "ج", page: 273, targetPage: 274 },
            { letter: "ح", page: 274, targetPage: 275 },
            { letter: "خ", page: 276, targetPage: 277 },
            { letter: "د", page: 277, targetPage: 278 },
            { letter: "ذ", page: 278, targetPage: 279 },
            { letter: "ر", page: 279, targetPage: 280 },
            { letter: "ز", page: 282, targetPage: 283 },
            { letter: "س", page: 282, targetPage: 283 },
            { letter: "ش", page: 287, targetPage: 288 },
            { letter: "ص", page: 289, targetPage: 290 },
            { letter: "ض", page: 290, targetPage: 291 },
            { letter: "ط", page: 290, targetPage: 291 },
            { letter: "ظ", page: 291, targetPage: 292 },
            { letter: "ع", page: 291, targetPage: 292 },
            { letter: "غ", page: 294, targetPage: 295 },
            { letter: "ف", page: 296, targetPage: 297 },
            { letter: "ق", page: 297, targetPage: 298 },
            { letter: "ک", page: 299, targetPage: 300 },
            { letter: "ل", page: 300, targetPage: 301 },
            { letter: "م", page: 301, targetPage: 302 },
            { letter: "ن", page: 302, targetPage: 303 },
            { letter: "و", page: 306, targetPage: 307 },
            { letter: "ھ", page: 310, targetPage: 311 },
            { letter: "ی", page: 311, targetPage: 312 },
        ]
    },
    {
        id: 26,
        title: "ن",
        letterKey: "ن",
        page: 312,
        targetPage: 313,
        subLetters: [
            { letter: "آ", page: 312, targetPage: 313 },
            { letter: "ا", page: 312, targetPage: 313 },
            { letter: "ب", page: 315, targetPage: 316 },
            { letter: "ت", page: 316, targetPage: 317 },
            { letter: "ث", page: 317, targetPage: 318 },
            { letter: "ج", page: 317, targetPage: 318 },
            { letter: "ح", page: 318, targetPage: 319 },
            { letter: "خ", page: 319, targetPage: 320 },
            { letter: "د", page: 320, targetPage: 321 },
            { letter: "ذ", page: 320, targetPage: 321 },
            { letter: "ر", page: 321, targetPage: 322 },
            { letter: "ز", page: 321, targetPage: 322 },
            { letter: "س", page: 322, targetPage: 323 },
            { letter: "ش", page: 324, targetPage: 325 },
            { letter: "ص", page: 325, targetPage: 326 },
            { letter: "ض", page: 326, targetPage: 327 },
            { letter: "ط", page: 327, targetPage: 328 },
            { letter: "ظ", page: 327, targetPage: 328 },
            { letter: "ع", page: 328, targetPage: 329 },
            { letter: "غ", page: 330, targetPage: 331 },
            { letter: "ف", page: 330, targetPage: 331 },
            { letter: "ق", page: 331, targetPage: 332 },
            { letter: "ک", page: 333, targetPage: 334 },
            { letter: "ل", page: 335, targetPage: 336 },
            { letter: "م", page: 335, targetPage: 336 },
            { letter: "ن", page: 336, targetPage: 337 },
            { letter: "و", page: 337, targetPage: 338 },
            { letter: "ھ", page: 339, targetPage: 340 },
            { letter: "ی", page: 339, targetPage: 340 },
        ]
    },
    {
        id: 27,
        title: "و",
        letterKey: "و",
        page: 340,
        targetPage: 341,
        subLetters: [
            { letter: "ا", page: 340, targetPage: 341 },
            { letter: "ب", page: 341, targetPage: 342 },
            { letter: "ت", page: 341, targetPage: 342 },
            { letter: "ث", page: 342, targetPage: 343 },
            { letter: "ج", page: 342, targetPage: 343 },
            { letter: "ح", page: 343, targetPage: 344 },
            { letter: "د", page: 343, targetPage: 344 },
            { letter: "ر", page: 343, targetPage: 344 },
            { letter: "ز", page: 344, targetPage: 345 },
            { letter: "س", page: 345, targetPage: 346 },
            { letter: "ص", page: 345, targetPage: 346 },
            { letter: "ض", page: 346, targetPage: 347 },
            { letter: "ط", page: 346, targetPage: 347 },
            { letter: "ع", page: 346, targetPage: 347 },
            { letter: "ف", page: 347, targetPage: 348 },
            { letter: "ق", page: 347, targetPage: 348 },
            { letter: "ک", page: 347, targetPage: 348 },
            { letter: "ل", page: 348, targetPage: 349 },
            { letter: "و", page: 348, targetPage: 349 },
            { letter: "ھ", page: 348, targetPage: 349 },
            { letter: "ی", page: 349, targetPage: 349 },
        ]
    },
    {
        id: 28,
        title: "ھ",
        letterKey: "ھ",
        page: 349,
        targetPage: 350,
        subLetters: [
            { letter: "ا", page: 349, targetPage: 350 },
            { letter: "ب", page: 351, targetPage: 352 },
            { letter: "ج", page: 351, targetPage: 352 },
            { letter: "د", page: 351, targetPage: 352 },
            { letter: "ذ", page: 352, targetPage: 353 },
            { letter: "ر", page: 352, targetPage: 353 },
            { letter: "ز", page: 352, targetPage: 353 },
            { letter: "ش", page: 352, targetPage: 353 },
            { letter: "ض", page: 352, targetPage: 353 },
            { letter: "ل", page: 353, targetPage: 354 },
            { letter: "م", page: 353, targetPage: 354 },
            { letter: "ن", page: 353, targetPage: 354 },
            { letter: "و", page: 354, targetPage: 355 },
            { letter: "ی", page: 354, targetPage: 355 },
        ]
    },
    {
        id: 29,
        title: "ی",
        letterKey: "ی",
        page: 354,
        targetPage: 355,
        subLetters: [
            { letter: "ا", page: 355, targetPage: 356 },
            { letter: "ب", page: 357, targetPage: 358 },
            { letter: "ت", page: 362, targetPage: 363 },
            { letter: "ث", page: 371, targetPage: 372 },
            { letter: "ج", page: 372, targetPage: 373 },
            { letter: "ح", page: 375, targetPage: 376 },
            { letter: "خ", page: 381, targetPage: 382 },
            { letter: "د", page: 386, targetPage: 387 },
            { letter: "ذ", page: 388, targetPage: 389 },
            { letter: "ر", page: 390, targetPage: 391 },
            { letter: "ز", page: 395, targetPage: 396 },
            { letter: "س", page: 397, targetPage: 398 },
            { letter: "ش", page: 407, targetPage: 408 },
            { letter: "ص", page: 410, targetPage: 411 },
            { letter: "ض", page: 415, targetPage: 416 },
            { letter: "ط", page: 417, targetPage: 418 },
            { letter: "ظ", page: 419, targetPage: 420 },
            { letter: "ع", page: 420, targetPage: 421 },
            { letter: "غ", page: 427, targetPage: 428 },
            { letter: "ف", page: 430, targetPage: 431 },
            { letter: "ق", page: 434, targetPage: 435 },
            { letter: "ک", page: 439, targetPage: 440 },
            { letter: "ل", page: 444, targetPage: 445 },
            { letter: "م", page: 448, targetPage: 449 },
            { letter: "ن", page: 452, targetPage: 453 },
            { letter: "و", page: 459, targetPage: 460 },
            { letter: "ھ", page: 466, targetPage: 467 },
            { letter: "ی", page: 469, targetPage: 470 },
        ]
    },
];