export interface SubLetterItem {
    letter: string;
    page: number;
}

export interface IndexItem {
    id: number;
    title: string;
    letterKey: string;
    page: number;
    targetPage?: number;
    subLetters?: SubLetterItem[];
}

export const PDF_INDEX: IndexItem[] = [
    {
        id: 1,
        title: "اٰ",
        letterKey: "اٰ",
        page: 3,
        targetPage: 4,
        subLetters: [
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "خ", page: 12 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 5 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ص", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ی", page: 91 },
        ]
    },
    {
        id: 2,
        title: "ا (الف)",
        letterKey: "ا",
        page: 3,
        targetPage: 4,
        subLetters: [
            { letter: "ء", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 12 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 5 },
            { letter: "ص", page: 5 },
            { letter: "ض", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 3,
        title: "ب",
        letterKey: "ب",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ء", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 12 },
            { letter: "د", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 5 },
            { letter: "ص", page: 5 },
            { letter: "ض", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 4,
        title: "ت",
        letterKey: "ت",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 12 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 5 },
            { letter: "ص", page: 5 },
            { letter: "ض", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 5,
        title: "ث",
        letterKey: "ث",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ج", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 6,
        title: "ج",
        letterKey: "ج",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ء", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ث", page: 5 },
            { letter: "ح", page: 5 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 7,
        title: "ح",
        letterKey: "ح",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 5 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 5 },
            { letter: "ص", page: 5 },
            { letter: "ض", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 8,
        title: "خ",
        letterKey: "خ",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 5 },
            { letter: "ص", page: 5 },
            { letter: "ض", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 9,
        title: "د",
        letterKey: "د",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 12 },
            { letter: "ر", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 10,
        title: "ذ",
        letterKey: "ذ",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 11,
        title: "ر",
        letterKey: "ر",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ء", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 4 },
            { letter: "ج", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 4 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 4 },
            { letter: "ف", page: 4 },
            { letter: "ق", page: 4 },
            { letter: "ک", page: 5 },
            { letter: "م", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 12,
        title: "ز",
        letterKey: "ز",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ج", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ق", page: 4 },
            { letter: "ک", page: 5 },
            { letter: "م", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 13,
        title: "س",
        letterKey: "س",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "ج", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ق", page: 4 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 14,
        title: "ش",
        letterKey: "ش",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ء", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 5 },
            { letter: "ج", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ط", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ق", page: 4 },
            { letter: "ک", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 15,
        title: "ص",
        letterKey: "ص",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 5 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 91 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 16,
        title: "ض",
        letterKey: "ض",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ل", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 17,
        title: "ط",
        letterKey: "ط",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "س", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 18,
        title: "ظ",
        letterKey: "ظ",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ع", page: 5 },
            { letter: "ف", page: 4 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "ھ", page: 5 },
        ]
    },
    {
        id: 19,
        title: "ع",
        letterKey: "ع",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ت", page: 4 },
            { letter: "ث", page: 4 },
            { letter: "ج", page: 4 },
            { letter: "د", page: 5 },
            { letter: "ذ", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 4 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 4 },
            { letter: "ظ", page: 4 },
            { letter: "ف", page: 4 },
            { letter: "ق", page: 4 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 4 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 20,
        title: "غ",
        letterKey: "غ",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 4 },
            { letter: "ث", page: 4 },
            { letter: "د", page: 5 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 4 },
            { letter: "س", page: 5 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 4 },
            { letter: "ف", page: 4 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 4 },
            { letter: "و", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 21,
        title: "ف",
        letterKey: "ف",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ء", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ج", page: 4 },
            { letter: "ح", page: 5 },
            { letter: "خ", page: 5 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "ز", page: 4 },
            { letter: "س", page: 4 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 22,
        title: "ق",
        letterKey: "ق",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "ف", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 23,
        title: " ک",
        letterKey: " ک",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ذ", page: 4 },
            { letter: "ر", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ش", page: 4 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "ف", page: 5 },
            { letter: "ل", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 24,
        title: "ل",
        letterKey: "ل",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ذ", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 25,
        title: "م",
        letterKey: "م",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 4 },
            { letter: "خ", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ذ", page: 4 },
            { letter: "ر", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 4 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 26,
        title: "ن",
        letterKey: "ن",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "آ", page: 5 },
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 4 },
            { letter: "خ", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ذ", page: 4 },
            { letter: "ر", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "غ", page: 5 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 4 },
            { letter: "م", page: 5 },
            { letter: "ن", page: 5 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 27,
        title: "و",
        letterKey: "و",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ر", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 4 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 28,
        title: "ھ",
        letterKey: "ھ",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "د", page: 4 },
            { letter: "ذ", page: 4 },
            { letter: "ر", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "ش", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ل", page: 4 },
            { letter: "م", page: 4 },
            { letter: "ن", page: 4 },
            { letter: "و", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
    {
        id: 29,
        title: "ی",
        letterKey: "ی",
        page: 61,
        targetPage: 62,
        subLetters: [
            { letter: "ا", page: 5 },
            { letter: "ب", page: 5 },
            { letter: "ت", page: 5 },
            { letter: "ث", page: 5 },
            { letter: "ج", page: 5 },
            { letter: "ح", page: 4 },
            { letter: "خ", page: 4 },
            { letter: "د", page: 4 },
            { letter: "ذ", page: 4 },
            { letter: "ر", page: 4 },
            { letter: "ز", page: 5 },
            { letter: "س", page: 4 },
            { letter: "ش", page: 4 },
            { letter: "ص", page: 4 },
            { letter: "ض", page: 4 },
            { letter: "ط", page: 5 },
            { letter: "ظ", page: 5 },
            { letter: "ع", page: 4 },
            { letter: "غ", page: 4 },
            { letter: "ف", page: 5 },
            { letter: "ق", page: 5 },
            { letter: "ک", page: 5 },
            { letter: "ل", page: 4 },
            { letter: "م", page: 4 },
            { letter: "ن", page: 4 },
            { letter: "و", page: 5 },
            { letter: "ھ", page: 5 },
            { letter: "ی", page: 5 },
        ]
    },
];